[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run client-install && npm run server-install && cd client && npm run build"

[deploy]
startCommand = "npm run server"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
